
# [Default]

data:
  dataset: "electricity" # [electricity]
  day_first: False

compression:
  compression_rate: 0.5
  feature_retention_strategy: "pca" # [pca or select]
  history_block_size: 2
  data_to_model_ratio: 1.0
  history_to_feature_ratio: 1.0
  # selected_features: ['U98', 'U42', 'U69']

train:
  epochs: 100 # [100]
  batch_size: 16 # [8]
  lr: 1.0e-3
  window_length: 168
  device: "cuda:0" # [cuda:0]

diffusion:
  layers: 4 
  channels: 64 # [64]
  nheads: 8 # [8]
  diffusion_embedding_dim: 128 # [128]
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"
  is_linear: True

model:
  timeemb: 128
  featureemb: 16
  training_feature_sample_size: 64